In [1]:
import random
import numpy as np

In [2]:
num = random.randrange(1,10,1)
num

9

In [3]:
arr = np.array([[i + random.randrange(1,10,1) ,i+random.randrange(1,10,1) ,i - random.randrange(1,10,1)] for i in range(0,3)])

In [4]:
arr

array([[ 1,  9, -6],
       [ 2,  4, -6],
       [ 8,  9, -7]])

In [5]:
arr.shape

(3, 3)

In [6]:
#question 2 float nparray to int
arr = np.array([1.1,2.2,3.3])
arr.dtype

dtype('float64')

In [7]:
arr.astype(np.int64)

array([1, 2, 3])

In [8]:
#question 3 fancy indexing to get even from list [1,2,3,4,5,6]
arr = np.array([1,2,3,4,5,6])
arr2 = arr[1::2].copy()
arr2

array([2, 4, 6])

In [9]:
#q4 1d array to 3x3 matrix of size 9
#basic factorials of 9 are (1,9) (9,1) (3,3)
#using matrix shape shift
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
arr = arr.reshape((3,3))
arr

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#already done exercize on boolean indexing but ok nvm
arr = np.arange(0,60,2)
print(f"this is the array orinally: {arr} \n\n")
print(f"this is part of array that is greater then 50: {arr[arr>50]}")

this is the array orinally: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58] 


this is part of array that is greater then 50: [52 54 56 58]
