function  
np.zeros((x,y))  
np.ones((dimensions x,y))  
np.full((dimensions x,y), number to be filled **i.e, 7**)  

In [3]:
import numpy as np
a = np.zeros((3,3))
b = np.ones((3,3))
c = np.full((3,3),7)

In [6]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])