function  
np.zeros((x,y))  
np.ones((dimensions x,y))  
np.full((dimensions x,y), number to be filled **i.e, 7**)  

In [1]:
import numpy as np
a = np.zeros((3,3))
b = np.ones((3,3))
c = np.full((3,3),7)

In [2]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
c

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [5]:
#to be exact this is how all of the functions work here
np.zeros((3, 3))    # 3x3 array of zeros
np.ones((2, 4))     # 2x4 array of ones
np.full((2, 2), 7)  # 2x2 array filled with 7
np.eye(4)           # 4x4 identity matrix
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**<h1> ATTRIBUTES </h1>**

In [7]:
#the attributes of an numpy array
#shape(rows and columns) size dimension/ndim datatype/dtype
arr = np.array([[1,2,3,4,5],[11,12,13,14,15]])

In [8]:
arr.shape

(2, 5)

In [9]:
arr.size

10

In [10]:
arr.ndim

2

In [11]:
arr.dtype

dtype('int64')

**<h1> TYPE CONVERSION </h1>**   

In [21]:
#type conversion is only possible from:
#number --> number != string
arr = np.arange(1,7,8)
print(arr.dtype)
arr2 = arr.astype(np.float64) #other types--> float32 and int32
arr2.dtype 

int64


dtype('float64')

**<h1>CHANGING SHAPE/DIMENSION(NDIM) ATTRIBUTE</h1>**

In [34]:
arr = np.array(([[i,i+1] for i in range(1,10)]))
arr2 = np.array(([[i,i+1] for i in range(1,10)]))
arr.shape #--> 9,2 ,means 9*2 elements take factor of 18 (2,9) (3,6) (6,8) only this is possible
print(arr.reshape((3,6)))


[[ 1  2  2  3  3  4]
 [ 4  5  5  6  6  7]
 [ 7  8  8  9  9 10]]


In [35]:
#flatten 2D --> 1D
arr.flatten()

array([ 1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,  9,
       10])

In [36]:
#some fun ;)
np.unique(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.unique(arr2, axis = 0) #axis is the index for where

array([[ 1,  2],
       [ 2,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])