In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
b = a[:4]

In [5]:
b[0] = 999
b

array([999,   2,   3,   4])

In [6]:
a

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

<h3>REFERENCES NOT A COPY</h3>
<p>to copy use .copy() method</p>

In [7]:
b = a[:4].copy()

In [11]:
b[1] = 1000
b #seperate memory allocation

array([ 999, 1000,    3,    4])

In [10]:
a

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

**hello** freiends today we learn *boolean masking*

In [14]:
#arr[condition]
arr = a.copy()
arr[arr>32]

array([999])

now we learn **<h7>DIRECT INDEXING</h7>**  

In [16]:
arr[[1,2,3,5]]

array([2, 3, 4, 6])

<h1>MULTIDIMENSIONAL-INDEXING AND AXIS</h1>